---
# Disable strict editor validation so `${{ secrets.* }}` expressions don't trigger
# "Context access might be invalid" warnings locally. GitHub evaluates these correctly.
# yaml-language-server: $schema: "none"

name: Integration Tests (AWS)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-aws:
    name: AWS integration tests
    runs-on: ubuntu-latest
    # Provide env at the job level; values come from repository secrets on GitHub
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ih-frontend/package-lock.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        working-directory: ih-frontend
        run: npm ci

      - name: Run integration tests (real AWS)
        working-directory: ih-frontend
        run: npm run test:integration
