---
name: Integration Tests (Mock AWS)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-mock-aws:
    name: Integration tests (LocalStack mock)
    runs-on: ubuntu-latest
    env:
      # Mock AWS credentials for LocalStack (no real AWS account needed)
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_S3_BUCKET: test-bucket
      AWS_ENDPOINT: http://localhost:4566
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
          configuration: |
            SERVICES=s3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ih-frontend/package-lock.json

      - name: Install dependencies
        working-directory: ih-frontend
        run: npm ci

      - name: Create S3 bucket in LocalStack
        run: |
          aws --endpoint-url=$AWS_ENDPOINT s3 mb s3://$AWS_S3_BUCKET || true

      - name: Run integration tests (LocalStack)
        working-directory: ih-frontend
        run: npm run test:integration
