---
# Disable YAML schema validation for this file in the editor so `${{ secrets.* }}` uses
# don't produce spurious 'Context access might be invalid' diagnostics. This file is
# intended to be executed manually (workflow_dispatch) on GitHub where secrets are defined.
# yaml-language-server: $schema: "none"
name: Integration Tests (real AWS)

on:
  workflow_dispatch:

jobs:
  integration-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd ih-frontend
          npm ci
      - name: Run integration tests (real AWS)
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd ih-frontend
          npm run test:integration
