name: Live TBO API Health Check

on:
  schedule:
    # Run every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - 'qa/scripts/healthcheck.sh'
      - '.github/workflows/live-tbo-health.yml'

jobs:
  health-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq curl

      - name: Run TBO Health Check
        env:
          TBO_CLIENT_ID: ${{ secrets.TBO_CLIENT_ID }}
          TBO_USERNAME: ${{ secrets.TBO_USERNAME }}
          TBO_PASSWORD: ${{ secrets.TBO_PASSWORD }}
          END_USER_IP: ${{ secrets.END_USER_IP }}
          DEPART_DATE: "2025-11-20"
          CHECKIN: "2025-11-20"
          BANGALORE_ID: "115936"
        run: |
          bash qa/scripts/healthcheck.sh

      - name: Report failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue_title = `🚨 TBO API Health Check Failed - ${new Date().toISOString()}`;
            const issue_body = `
            ## TBO API Health Check Failure
            
            **Time:** ${new Date().toISOString()}
            **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            The automated health check for TBO APIs has failed. Please investigate:
            
            - Check TBO API status
            - Verify credentials are still valid
            - Review the workflow logs for detailed error messages
            
            ### Actions to take:
            1. Review the workflow run logs
            2. Test APIs manually using Postman collection in \`qa/postman/\`
            3. Check TBO dashboard for any service disruptions
            4. Verify network connectivity and proxy settings
            
            ---
            *This issue was automatically created by the TBO Health Check workflow*
            `;
            
            // Create an issue
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issue_title,
              body: issue_body,
              labels: ['tbo-api', 'health-check', 'automated']
            });
